<!--
 * @Author: wjf
 * @Date: 2022-08-25 11:14:50
 * @LastEditTime: 2022-08-29 09:48:45
 * @LastEditors: wjf
 * @Description:表格的多行合并练习
-->
<template>
  <div>
    <!-- <h2>javaScriptPretice</h2> -->
    <div class="main">
      <table class="table">
        <tr>
          <th width="180px">备件信息</th>
          <th width="180px">备件信息</th>
          <th width="180px">备件信息</th>
          <th width="180px">备件信息</th>
          <th width="180px">备件信息</th>
        </tr>
      </table>
      <div v-for="item in dataList" :key="item.orderId">
        <div class="top">
           <span class="headTime">
             {{item.createTime}}
           </span>
            <span class="headtext">备件领用单号:
               <span class="text">{{ item.orderCode }}</span>
            </span>

            <span class="headtext">内部单号:
            <span class="text">{{ item.orderCode }}</span>
            </span>

            <span class="headtext">企业:
              <span class="text">{{ item.orderCode }}</span>
            </span>

            <span class="headtext">客户:
            <span class="text">{{ item.orderCode }}</span>
            </span>

            <span class="headtext">企业:
            <span class="text">{{ item.orderCode }}</span>
            </span>
        </div>
        <tableBox :tableList='item.itemVos' :orderJson='item'/>
      </div>
    </div>
  </div>
</template>

<script>
import tableBox from './components/tableBox.vue'
export default {
  components: { tableBox },
  name: 'LearnIndex',

  data () {
    return {
      dataList: [
        {
          orderId: '1548843962686869506',
          companyId: '1495580001778819074',
          orderCode: 'CO22071853949',
          custOrderNo: '12',
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-07-18 09:35:52',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 3.26,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1548843963370541058',
              orderId: '1548843962686869506',
              custspId: '1524720553933762562',
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '11',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-07-21',
              customerDeliveryCycleStr: '2022年07月21日',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1548843963370541058',
              orderId: '1548843962686869506',
              custspId: '1524720553933762562',
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '11',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-07-21',
              customerDeliveryCycleStr: '2022年07月21日',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1548843963370541058',
              orderId: '1548843962686869506',
              custspId: '1524720553933762562',
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '11',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-07-21',
              customerDeliveryCycleStr: '2022年07月21日',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1548843963370541058',
              orderId: '1548843962686869506',
              custspId: '1524720553933762562',
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '11',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-07-21',
              customerDeliveryCycleStr: '2022年07月21日',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1548843963370541058',
              orderId: '1548843962686869506',
              custspId: '1524720553933762562',
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '11',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-07-21',
              customerDeliveryCycleStr: '2022年07月21日',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '2',
          auditStatusStr: '审批通过',
          businessKey: '220718000006',
          taskId: null,
          addressVo: {
            orderAddressId: '1548843963173408770',
            orderId: '1548843962686869506',
            userId: '1480800419158700034',
            receiveGoodsPerson: '母公司2',
            receiveGoodsPhone: '18702936541',
            province: '河北省',
            city: '秦皇岛市',
            area: '山海关区',
            address: '13124',
            orderAddress: '河北省秦皇岛市山海关区13124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-07-18 09:35:52',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-07-18 09:35:52',
            type: '1'
          },
          receiveGoodsPerson: '母公司2',
          platformSource: '4',
          platformSourceStr: 'webshop'
        },
        {
          orderId: '1536970062298378241',
          companyId: '1495664574898380802',
          orderCode: 'CO22061592986',
          custOrderNo: null,
          companyName: '测试企业4',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-06-15 15:13:13',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 68.46,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1536970063003021314',
              orderId: '1536970062298378241',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 21,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 68.46,
              goodsMoney: 68.46,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA16231',
              oldGoodsName: '测试子公司',
              oldSpecification: '把',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '无牌',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-06-18',
              customerDeliveryCycleStr: '2022年06月18日',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '2',
          auditStatusStr: '审批通过',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1536970062776528898',
            orderId: '1536970062298378241',
            userId: '1480800419158700034',
            receiveGoodsPerson: '子企业收货地址1',
            receiveGoodsPhone: '18765988451',
            province: '河北省',
            city: '石家庄市',
            area: '桥西区',
            address: '擦手',
            orderAddress: '河北省石家庄市桥西区擦手',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-06-15 15:13:13',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-06-15 15:13:13',
            type: '1'
          },
          receiveGoodsPerson: '子企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1536545469782454274',
          companyId: '1495580001778819074',
          orderCode: 'CO22061431518',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-06-14 11:06:02',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 3.26,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1536545470646480897',
              orderId: '1536545469782454274',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '1',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: '2022-06-24',
              customerDeliveryCycleStr: '2022年06月24日',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '2',
          auditStatusStr: '审批通过',
          businessKey: '220614000043',
          taskId: null,
          addressVo: {
            orderAddressId: '1536545470373851137',
            orderId: '1536545469782454274',
            userId: '1480800419158700034',
            receiveGoodsPerson: '王晶',
            receiveGoodsPhone: '15987456321',
            province: '北京市',
            city: '北京市',
            area: '东城区',
            address: '沙发',
            orderAddress: '北京市北京市东城区沙发',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-06-14 11:06:02',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-06-14 11:06:02',
            type: '1'
          },
          receiveGoodsPerson: '王晶',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1529344133485068289',
          companyId: '1495664574898380802',
          orderCode: 'CO22052548300',
          custOrderNo: null,
          companyName: '测试企业4',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-25 14:10:30',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 3.26,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1529344134453952514',
              orderId: '1529344133485068289',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA16231',
              oldGoodsName: '测试子公司',
              oldSpecification: '把',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '无牌',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1529344134114213890',
            orderId: '1529344133485068289',
            userId: '1480800419158700034',
            receiveGoodsPerson: '子企业收货地址1',
            receiveGoodsPhone: '18765988451',
            province: '河北省',
            city: '石家庄市',
            area: '桥西区',
            address: '擦手',
            orderAddress: '河北省石家庄市桥西区擦手',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-25 14:10:30',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-25 14:10:30',
            type: '1'
          },
          receiveGoodsPerson: '子企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524729539466731522',
          companyId: '1495580001778819074',
          orderCode: 'CO22051254529',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 20:33:45',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 4.46,
          status: null,
          itemNum: 2,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524729539902939137',
              orderId: '1524729539466731522',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: null,
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1524729539928104961',
              orderId: '1524729539466731522',
              custspId: null,
              goodsSpuId: '2462202964505092096',
              goodsSkuId: '4462202965390090240',
              goodsCode: 'SNA03279',
              goodsErpCode: null,
              goodsName: '积分兑换商品',
              brandName: '上海萨姆森',
              goodsModel: 'QWE01',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 0.1,
              transactionPrice: 0.1,
              originalTransactionPrice: 0.1,
              goodsNum: 12,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 1.2,
              goodsMoney: 1.2,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/commonAttachment/1651199366849/11.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA15385',
              oldGoodsName: '手机图片',
              oldSpecification: '克',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '潮牌',
              goodsUnit: '把',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524729539793887233',
            orderId: '1524729539466731522',
            userId: '1480800419158700034',
            receiveGoodsPerson: '母企业收货地址1',
            receiveGoodsPhone: '18702936594',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '4124124',
            orderAddress: '天津市天津市辖县静海县4124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 20:33:45',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 20:33:45',
            type: '1'
          },
          receiveGoodsPerson: '母企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524729222842916866',
          companyId: '1495580001778819074',
          orderCode: 'CO22051258513',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 20:32:30',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 1587.62,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524729223396564994',
              orderId: '1524729222842916866',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 487,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 1587.62,
              goodsMoney: 1587.62,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA16231',
              oldGoodsName: '测试子公司',
              oldSpecification: '把',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '无牌',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524729223279124482',
            orderId: '1524729222842916866',
            userId: '1480800419158700034',
            receiveGoodsPerson: '母企业收货地址1',
            receiveGoodsPhone: '18702936594',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '4124124',
            orderAddress: '天津市天津市辖县静海县4124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 20:32:30',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 20:32:30',
            type: '1'
          },
          receiveGoodsPerson: '母企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524729167847202817',
          companyId: '1495580001778819074',
          orderCode: 'CO22051282643',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 20:32:16',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 3.26,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524729168455376897',
              orderId: '1524729167847202817',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 1,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 3.26,
              goodsMoney: 3.26,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SGKMP009B33',
              oldGoodsName:
                'ABB  S200 微型断路器 S202-C2 ( 只 ) S202-C2$系列:S200',
              oldSpecification: '默认规格值',
              oldModel: 'S202-C2$系列:S200',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: 'ABB',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: null,
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524729168316964865',
            orderId: '1524729167847202817',
            userId: '1480800419158700034',
            receiveGoodsPerson: '母企业收货地址1',
            receiveGoodsPhone: '18702936594',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '4124124',
            orderAddress: '天津市天津市辖县静海县4124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 20:32:16',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 20:32:16',
            type: '1'
          },
          receiveGoodsPerson: '母企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524717393668304897',
          companyId: '1495664574898380802',
          orderCode: 'CO22051298558',
          custOrderNo: null,
          companyName: '测试企业4',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 19:45:29',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 40.32,
          status: null,
          itemNum: 2,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524717394192592898',
              orderId: '1524717393668304897',
              custspId: null,
              goodsSpuId: '2462202964505092096',
              goodsSkuId: '4462202965390090240',
              goodsCode: 'SNA03279',
              goodsErpCode: null,
              goodsName: '积分兑换商品',
              brandName: '上海萨姆森',
              goodsModel: 'QWE01',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 0.1,
              transactionPrice: 0.1,
              originalTransactionPrice: 0.1,
              goodsNum: 12,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 1.2,
              goodsMoney: 1.2,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/commonAttachment/1651199366849/11.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA15385',
              oldGoodsName: '手机图片',
              oldSpecification: '克',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '潮牌',
              goodsUnit: '把',
              sellingUnit: null,
              oldRemark: '41',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            },
            {
              orderItemId: '1524717394196787201',
              orderId: '1524717393668304897',
              custspId: null,
              goodsSpuId: '2312243351153807360',
              goodsSkuId: '312243351153807360',
              goodsCode: 'SSFWG006D4A',
              goodsErpCode: null,
              goodsName:
                '宁波兆比特 兆比特 多模国产光纤(6芯)（轻铠） GYXTW-6A1b (米)（运费面议） 中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              brandName: '宁波兆比特',
              goodsModel:
                '中心束管式轻铠类光缆(GYXTW)$规格:多模、单模$芯数:4芯、6芯、8芯',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 3.26,
              transactionPrice: 3.26,
              originalTransactionPrice: 3.26,
              goodsNum: 12,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 39.12,
              goodsMoney: 39.12,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/thirdToForth/307962735832657920/rBAAv12mrZuAEzX4AABXbkBMivQ147.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA16231',
              oldGoodsName: '测试子公司',
              oldSpecification: '把',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '无牌',
              goodsUnit: 'PCS',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524717394058375169',
            orderId: '1524717393668304897',
            userId: '1480800419158700034',
            receiveGoodsPerson: '母企业收货地址1',
            receiveGoodsPhone: '18702936594',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '4124124',
            orderAddress: '天津市天津市辖县静海县4124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 19:45:29',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 19:45:29',
            type: '1'
          },
          receiveGoodsPerson: '母企业收货地址1',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524675617360277505',
          companyId: '1495580001778819074',
          orderCode: 'CO22051285032',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 16:59:29',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 1.2,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524675617775513601',
              orderId: '1524675617360277505',
              custspId: null,
              goodsSpuId: '2462202964505092096',
              goodsSkuId: '4462202965390090240',
              goodsCode: 'SNA03279',
              goodsErpCode: null,
              goodsName: '积分兑换商品',
              brandName: '上海萨姆森',
              goodsModel: 'QWE01',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 0.1,
              transactionPrice: 0.1,
              originalTransactionPrice: 0.1,
              goodsNum: 12,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 1.2,
              goodsMoney: 1.2,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/commonAttachment/1651199366849/11.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA15385',
              oldGoodsName: '手机图片',
              oldSpecification: '克',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '潮牌',
              goodsUnit: '把',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524675617670656002',
            orderId: '1524675617360277505',
            userId: '1480800419158700034',
            receiveGoodsPerson: '黄涛',
            receiveGoodsPhone: '18702936548',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '124124',
            orderAddress: '天津市天津市辖县静海县124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 16:59:29',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 16:59:29',
            type: '1'
          },
          receiveGoodsPerson: '黄涛',
          platformSource: '0',
          platformSourceStr: '未知'
        },
        {
          orderId: '1524656622187933697',
          companyId: '1495580001778819074',
          orderCode: 'CO22051248225',
          custOrderNo: null,
          companyName: '余世琪测试企业(new)',
          orderStatus: '10',
          orderStatusStr: '待审核',
          lclbFrontDeskOrderStatusStr: '待受理',
          deliveryStatus: '10',
          createTime: '2022-05-12 15:44:00',
          applyUserName: '余世琪',
          username: null,
          userId: '1480800419158700034',
          money: 1.2,
          status: null,
          itemNum: 1,
          contractCode: null,
          billCreateStatus: null,
          itemVos: [
            {
              orderItemId: '1524656622624141313',
              orderId: '1524656622187933697',
              custspId: null,
              goodsSpuId: '2462202964505092096',
              goodsSkuId: '4462202965390090240',
              goodsCode: 'SNA03279',
              goodsErpCode: null,
              goodsName: '积分兑换商品',
              brandName: '上海萨姆森',
              goodsModel: 'QWE01',
              tagPrice: null,
              goodsPrice: null,
              goodsPriceDiscount: null,
              sellingPrice: 0.1,
              transactionPrice: 0.1,
              originalTransactionPrice: 0.1,
              goodsNum: 12,
              commodityType: null,
              inventoryQuantity: null,
              discount: 100,
              money: 1.2,
              goodsMoney: 1.2,
              expressFee: 0,
              logisticsTemplate: null,
              freightTemplateId: null,
              goodsUrl:
                'https://devzk.oss-cn-hangzhou.aliyuncs.com/commonAttachment/1651199366849/11.png',
              goodsRemarks: null,
              distribution: null,
              supplyCommodityCode: null,
              commodityAttributeValueVos: null,
              goodsRowNo: null,
              specification: '默认规格：默认规格值',
              remark: null,
              oldGoodsCode: 'SMA15385',
              oldGoodsName: '手机图片',
              oldSpecification: '克',
              oldModel: '304刚',
              oldEdition: null,
              oldConfiguration: null,
              oldBrand: '潮牌',
              goodsUnit: '把',
              sellingUnit: null,
              oldRemark: '',
              companyId: null,
              userId: null,
              orderCode: null,
              commodityPurchasePrice: null,
              customerDeliveryCycle: null,
              customerDeliveryCycleStr: '-',
              deliveryGoodsNum: null
            }
          ],
          auditStatus: '0',
          auditStatusStr: '等待提交',
          businessKey: null,
          taskId: null,
          addressVo: {
            orderAddressId: '1524656622515089410',
            orderId: '1524656622187933697',
            userId: '1480800419158700034',
            receiveGoodsPerson: '黄涛',
            receiveGoodsPhone: '18702936548',
            province: '天津市',
            city: '天津市辖县',
            area: '静海县',
            address: '124124',
            orderAddress: '天津市天津市辖县静海县124124',
            corporateClientsId: null,
            createUser: '1480800419158700034',
            createTime: '2022-05-12 15:44:00',
            modifyUser: '1480800419158700034',
            modifyTime: '2022-05-12 15:44:00',
            type: '1'
          },
          receiveGoodsPerson: '黄涛',
          platformSource: '0',
          platformSourceStr: '未知'
        }
      ]
    }
  },
  component: { tableBox },

  mounted () {},

  methods: {
    deleteRow (index, rows) {
      rows.splice(index, 1)
    }
  }
}
</script>

<style lang="scss" scoped>
.main {
  font-family: Helvetica Neue, Helvetica, PingFang SC, Hiragino Sans GB,
    Microsoft YaHei, SimSun, sans-serif;
  border: 1px solid #ebeef5;
  color: #303133;
  margin: 0 auto;
  font-size: 14px;
  width: 80%;
  .table {
    border-collapse: collapse;
    th {
      font-weight: 700;
      height: 40px;
      padding: 4px 10px;
      text-align: center;
      line-height: 40px;
      border: 1px solid #ebeef5;
      border-top: none;
      // border-bottom: none;

      &:last-child {
        border-right: none;
      }
      &:first-child {
        border-left: none;
      }
    }
  }
  .top {
    height: 50px;
    margin-top: 15px;
    line-height: 50px;
    background-color: #f5f7fa;
    border: 1px solid #ebeff6;
    border-left: none;
    border-right: none;

      .headtext {
        margin-left: 20px;
        color: #999;

      .text{
          color: #303133;
      }
      }
      .headTime{
        box-sizing: border-box;
        float: right;
        margin-right: 30px;
        color: #999999;
      }
  }

}
</style>
